window.stations_ids = new Map;
window.stations_ids.set('Southport Ave & Wrightwood Ave', '190')
window.stations_ids.set('Dearborn Pkwy & Delaware Pl', '140')
window.stations_ids.set('Lake Park Ave & 56th St', '345')
window.stations_ids.set('Racine Ave & 13th St', '136')
window.stations_ids.set('Clinton St & Roosevelt Rd', '57')
window.stations_ids.set('Prairie Ave & Garfield Blvd', '204')
window.stations_ids.set('Leavitt St & North Ave', '213')
window.stations_ids.set('Lincoln Ave & Armitage Ave', '94')
window.stations_ids.set('Wells St & Ohio St', '212')
window.stations_ids.set('Blackstone Ave & Hyde Park Blvd', '121')
window.stations_ids.set('Clark St & Elm St', '176')
window.stations_ids.set('Ashland Ave & Wrightwood Ave', '166')
window.stations_ids.set('Ogden Ave & Race Ave', '186')
window.stations_ids.set('Lincoln Ave & Belmont Ave', '131')
window.stations_ids.set('Larrabee St & North Ave', '27')
window.stations_ids.set('Michigan Ave & Lake St', '52')
window.stations_ids.set('Clark St & Waveland Ave', '165')
window.stations_ids.set('Desplaines St & Kinzie St', '56')
window.stations_ids.set('Ashland Ave & Blackhawk St', '333')
window.stations_ids.set('State St & Randolph St', '44')
window.stations_ids.set('California Ave & 21st St', '348')
window.stations_ids.set('Stave St & Armitage Ave', '185')
window.stations_ids.set('Ashland Ave & Belle Plaine Ave', '246')
window.stations_ids.set('Clarendon Ave & Leland Ave', '251')
window.stations_ids.set('Sheridan Rd & Irving Park Rd', '240')
window.stations_ids.set('Eckhart Park', '86')
window.stations_ids.set('Kingsbury St & Erie St', '74')
window.stations_ids.set('Damen Ave & Sunnyside Ave', '316')
window.stations_ids.set('State St & Kinzie St', '47')
window.stations_ids.set('Orleans St & Elm St', '23')
window.stations_ids.set('Halsted St & Archer Ave', '206')
window.stations_ids.set('Clark St & Winnemac Ave', '325')
window.stations_ids.set('May St & Cullerton St', '171')
window.stations_ids.set('Western Ave & Winnebago Ave', '116')
window.stations_ids.set('Paulina St & Diversey Pkwy', '163')
window.stations_ids.set('Lake Shore Dr & Ohio St', '99')
window.stations_ids.set('Sangamon St & Washington Blvd', '233')
window.stations_ids.set('Peoria St & Jackson Blvd', '134')
window.stations_ids.set('Cannon Dr & Fullerton Ave', '34')
window.stations_ids.set('Broadway & Belmont Ave', '296')
window.stations_ids.set('Rhodes Ave & 32nd St', '263')
window.stations_ids.set('State St & 16th St', '72')
window.stations_ids.set('Theater on the Lake', '177')
window.stations_ids.set('Jefferson St & Monroe St', '73')
window.stations_ids.set('Streeter Dr & Illinois St', '35')
window.stations_ids.set('California Ave & Milwaukee Ave', '123')
window.stations_ids.set('Pine Grove Ave & Irving Park Rd', '254')
window.stations_ids.set('Kedzie Ave & Palmer Ct', '290')
window.stations_ids.set('Sedgwick St & Huron St', '111')
window.stations_ids.set('Sheffield Ave & Fullerton Ave', '67')
window.stations_ids.set('Wolcott Ave & Polk St', '342')
window.stations_ids.set('Cityfront Plaza & N Water St', '196')
window.stations_ids.set('Normal Ave & Archer Ave', '209')
window.stations_ids.set('Lakeview Ave & Fullerton Pkwy', '313')
window.stations_ids.set('Michigan Ave & Jackson Blvd', '284')
window.stations_ids.set('Wilton Ave & Diversey Pkwy', '13')
window.stations_ids.set('Hermitage Ave & Polk St', '261')
window.stations_ids.set('Dayton St & North Ave', '60')
window.stations_ids.set('Franklin St & Lake St', '164')
window.stations_ids.set('State St & 35th St', '184')
window.stations_ids.set('Ashland Ave & Augusta Blvd', '30')
window.stations_ids.set('Ashland Ave & Grand Ave', '277')
window.stations_ids.set('Sheffield Ave & Addison St', '114')
window.stations_ids.set('King Dr & 47th St', '200')
window.stations_ids.set('State St & Pearson St', '106')
window.stations_ids.set('Damen Ave & Leland Ave', '242')
window.stations_ids.set('Southport Ave & Waveland Ave', '227')
window.stations_ids.set('Columbus Dr & Randolph St', '195')
window.stations_ids.set('Clark St & North Ave', '126')
window.stations_ids.set('Seeley Ave & Roscoe St', '308')
window.stations_ids.set('Clarendon Ave & Junior Ter', '245')
window.stations_ids.set('Paulina St & Montrose Ave', '297')
window.stations_ids.set('Lake Shore Dr & Wellington Ave', '157')
window.stations_ids.set('Sheffield Ave & Wrightwood Ave', '302')
window.stations_ids.set('Southport Ave & Clark St', '292')
window.stations_ids.set('Halsted St & Dickens Ave', '225')
window.stations_ids.set('Clark St & Schiller St', '301')
window.stations_ids.set('Kimbark Ave & 53rd St', '322')
window.stations_ids.set('Ellis Ave & 58th St', '328')
window.stations_ids.set('Wells St & Polk St', '175')
window.stations_ids.set('Blue Island Ave & 18th St', '129')
window.stations_ids.set('Paulina St & 18th St', '205')
window.stations_ids.set('Milwaukee Ave & Rockwell St', '222')
window.stations_ids.set('Emerald Ave & 31st St', '339')
window.stations_ids.set('Calumet Ave & 33rd St', '149')
window.stations_ids.set('Halsted St & Roscoe St', '299')
window.stations_ids.set('Wood St & Taylor St', '317')
window.stations_ids.set('LaSalle St & Washington St', '98')
window.stations_ids.set('Lincoln Ave & Belle Plaine Ave', '298')
window.stations_ids.set('Ashland Ave & Grace St', '347')
window.stations_ids.set('Halsted St & 37th St', '262')
window.stations_ids.set('Lake Park Ave & 47th St', '267')
window.stations_ids.set('Broadway & Berwyn Ave', '294')
window.stations_ids.set('Southport Ave & Clybourn Ave', '307')
window.stations_ids.set('Loomis St & Taylor St', '19')
window.stations_ids.set('State St & Van Buren St', '33')
window.stations_ids.set('Michigan Ave & 14th St', '168')
window.stations_ids.set('Aberdeen St & Jackson Blvd', '21')
window.stations_ids.set('Sheridan Rd & Lawrence Ave', '323')
window.stations_ids.set('Broadway & Argyle St', '295')
window.stations_ids.set('Clark St & Chicago Ave', '337')
window.stations_ids.set('Broadway & Cornelia Ave', '303')
window.stations_ids.set('Michigan Ave & Washington St', '43')
window.stations_ids.set('Wilton Ave & Belmont Ave', '117')
window.stations_ids.set('Sedgwick St & North Ave', '118')
window.stations_ids.set('Lincoln Ave & Leavitt St', '243')
window.stations_ids.set('State St & 33rd St', '148')
window.stations_ids.set('Michigan Ave & Congress Pkwy', '45')
window.stations_ids.set('Racine Ave & Fullerton Ave', '87')
window.stations_ids.set('Loomis St & Jackson Blvd', '146')
window.stations_ids.set('Sheffield Ave & Kingsbury St', '20')
window.stations_ids.set('Broadway & Wilson Ave', '293')
window.stations_ids.set('Southport Ave & Roscoe St', '229')
window.stations_ids.set('Halsted St & Blackhawk St', '331')
window.stations_ids.set('Woodlawn Ave & 55th St', '248')
window.stations_ids.set('Logan Blvd & Elston Ave', '258')
window.stations_ids.set('Halsted St & Willow St', '224')
window.stations_ids.set('Cottage Grove Ave & Oakwood Blvd', '265')
window.stations_ids.set('Millennium Park', '90')
window.stations_ids.set('Lincoln Ave & Eastwood Ave', '311')
window.stations_ids.set('Halsted St & Maxwell St', '282')
window.stations_ids.set('LaSalle St & Illinois St', '181')
window.stations_ids.set('Clark St & Wellington Ave', '156')
window.stations_ids.set('Lincoln Ave & Addison St', '330')
window.stations_ids.set('Morgan St & 31st St', '280')
window.stations_ids.set('Campbell Ave & North Ave', '160')
window.stations_ids.set('Sheridan Rd & Montrose Ave', '231')
window.stations_ids.set('Sheridan Rd & Buena Ave', '306')
window.stations_ids.set('Sheffield Ave & Wellington Ave', '115')
window.stations_ids.set('State St & Erie St', '110')
window.stations_ids.set('Michigan Ave & Pearson St', '25')
window.stations_ids.set('Wabash Ave & 8th St', '321')
window.stations_ids.set('Damen Ave & Madison St', '215')
window.stations_ids.set('Indiana Ave & 26th St', '147')
window.stations_ids.set('Greenview Ave & Diversey Pkwy', '319')
window.stations_ids.set('May St & Fulton St', '217')
window.stations_ids.set('Morgan Ave & 14th Pl', '137')
window.stations_ids.set('Franklin St & Arcade Pl', '287')
window.stations_ids.set('Kedzie Ave & Milwaukee Ave', '260')
window.stations_ids.set('Clark St & Montrose Ave', '234')
window.stations_ids.set('Franklin St & Jackson Blvd', '36')
window.stations_ids.set('Daley Center Plaza', '81')
window.stations_ids.set('Sedgwick St & Webster Ave', '143')
window.stations_ids.set('Wentworth Ave & Archer Ave', '120')
window.stations_ids.set('Halsted St & Madison St', '198')
window.stations_ids.set('Damen Ave & Cullerton St', '124')
window.stations_ids.set('Wabash Ave & Roosevelt Rd', '59')
window.stations_ids.set('Carpenter St & Huron St', '92')
window.stations_ids.set('McCormick Place', '62')
window.stations_ids.set('Indiana Ave & Roosevelt Rd', '255')
window.stations_ids.set('Ravenswood Ave & Montrose Ave', '238')
window.stations_ids.set('Indiana Ave & 40th St', '201')
window.stations_ids.set('Larrabee St & Armitage Ave', '288')
window.stations_ids.set('Larrabee St & Kingsbury St', '48')
window.stations_ids.set('Lincoln Ave & Fullerton Ave', '127')
window.stations_ids.set('Damen Ave & Division St', '130')
window.stations_ids.set('Clybourn Ave & Division St', '138')
window.stations_ids.set('Noble St & Milwaukee Ave', '29')
window.stations_ids.set('Morgan St & Lake St', '71')
window.stations_ids.set('Cottage Grove Ave & 51st St', '351')
window.stations_ids.set('Ashland Ave & Wellington Ave', '250')
window.stations_ids.set('900 W Harrison', '109')
window.stations_ids.set('Shore Drive & 55th St', '247')
window.stations_ids.set('Western Ave & 24th St', '281')
window.stations_ids.set('Broadway & Barry Ave', '300')
window.stations_ids.set('Western Ave & Leland Ave', '239')
window.stations_ids.set('Calumet Ave & 35th St', '335')
window.stations_ids.set('Fort Dearborn Dr & 31st St', '150')
window.stations_ids.set('Wentworth Ave & 24th St', '132')
window.stations_ids.set('California Ave & Division St', '216')
window.stations_ids.set('Clark St & Wrightwood Ave', '340')
window.stations_ids.set('Southport Ave & Wellington Ave', '153')
window.stations_ids.set('Wabash Ave & Cermak Rd', '42')
window.stations_ids.set('Damen Ave & Chicago Ave', '128')
window.stations_ids.set('Greenwood Ave & 47th St', '252')
window.stations_ids.set('LaSalle St & Jackson Blvd', '283')
window.stations_ids.set('Ravenswood Ave & Berteau Ave', '314')
window.stations_ids.set('Franklin St & Quincy St', '286')
window.stations_ids.set('Clark St & Congress Pkwy', '50')
window.stations_ids.set('Leavitt St & Armitage Ave', '309')
window.stations_ids.set('Wells St & Walton St', '46')
window.stations_ids.set('Ada St & Washington Blvd', '346')
window.stations_ids.set('Larrabee St & Webster Ave', '144')
window.stations_ids.set('Michigan Ave & Madison St', '197')
window.stations_ids.set('Racine Ave & 15th St', '274')
window.stations_ids.set('Damen Ave & Wellington Ave', '162')
window.stations_ids.set('Wood St & Grand Ave', '285')
window.stations_ids.set('Michigan Ave & Oak St', '85')
window.stations_ids.set('Damen Ave & Augusta Blvd', '183')
window.stations_ids.set('Ashland Ave & 13th St', '275')
window.stations_ids.set('Clinton St & Washington Blvd', '91')
window.stations_ids.set('Damen Ave & Grand Ave', '214')
window.stations_ids.set('Clifton Ave & Armitage Ave', '223')
window.stations_ids.set('Ravenswood Ave & Irving Park Rd', '244')
window.stations_ids.set('Franklin St & Chicago Ave', '31')
window.stations_ids.set('St Clair St & Erie St', '211')
window.stations_ids.set('Clifton Ave & Lawrence Ave', '253')
window.stations_ids.set('Ashland Ave & Lake St', '119')
window.stations_ids.set('Halsted St & Diversey Pkwy', '332')
window.stations_ids.set('May St & Randolph St', '88')
window.stations_ids.set('Ashland Ave & Chicago Ave', '350')
window.stations_ids.set('Stetson Ave & South Water St', '264')
window.stations_ids.set('Museum Campus', '97')
window.stations_ids.set('Wood St & Milwaukee Ave', '61')
window.stations_ids.set('Michigan Ave & 18th St', '273')
window.stations_ids.set('Halsted St & Wrightwood Ave', '349')
window.stations_ids.set('Wood St & North Ave', '16')
window.stations_ids.set('Morgan St & Polk St', '241')
window.stations_ids.set('Greenview Ave & Fullerton Ave', '188')
window.stations_ids.set('Racine Ave & Congress Pkwy', '32')
window.stations_ids.set('Cottage Grove Ave & 47th St', '336')
window.stations_ids.set('Green St & Milwaukee Ave', '84')
window.stations_ids.set('Larrabee St & Menomonee St', '28')
window.stations_ids.set('Claremont Ave & Hirsch St', '159')
window.stations_ids.set('Canal St & Jackson Blvd', '75')
window.stations_ids.set('Stockton Dr & Wrightwood Ave', '324')
window.stations_ids.set('Sedgwick St & Schiller St', '236')
window.stations_ids.set('Halsted St & Waveland Ave', '304')
window.stations_ids.set('Damen Ave & Cortland St', '219')
window.stations_ids.set('Canal St & Madison St', '174')
window.stations_ids.set('Clinton St & Madison St', '77')
window.stations_ids.set('Southport Ave & Belmont Ave', '154')
window.stations_ids.set('Halsted St & 35th St', '279')
window.stations_ids.set('Ogden Ave & Chicago Ave', '54')
window.stations_ids.set('Wells St & 19th St', '218')
window.stations_ids.set('Western Ave & 21st St', '203')
window.stations_ids.set('Halsted St & James M Rochford St', '55')
window.stations_ids.set('Sheffield Ave & Webster Ave', '327')
window.stations_ids.set('Calumet Ave & 18th St', '338')
window.stations_ids.set('Clinton St & 18th St', '170')
window.stations_ids.set('Canal St & Harrison St', '169')
window.stations_ids.set('May St & Taylor St', '22')
window.stations_ids.set('Dearborn St & Adams St', '37')
window.stations_ids.set('Orleans St & Merchandise Mart Plaza', '100')
window.stations_ids.set('Green St & Randolph St', '112')
window.stations_ids.set('Mies van der Rohe Way & Chicago Ave', '173')
window.stations_ids.set('Dearborn St & Monroe St', '49')
window.stations_ids.set('State St & Harrison St', '5')
window.stations_ids.set('Halsted St & 18th St', '202')
window.stations_ids.set('Leavitt St & Hirsch St', '315')
window.stations_ids.set('Racine Ave & Wrightwood Ave', '343')
window.stations_ids.set('Racine Ave & 18th St', '15')
window.stations_ids.set('Halsted St & 21st St', '135')
window.stations_ids.set('Ashland Ave & Division St', '210')
window.stations_ids.set('Pine Grove Ave & Addison St', '232')
window.stations_ids.set('Wells St & Erie St', '53')
window.stations_ids.set('Martin Luther King Dr & Oakwood Blvd', '179')
window.stations_ids.set('California Ave & Francis Pl', '259')
window.stations_ids.set('Lake Shore Dr & North Blvd', '268')
window.stations_ids.set('Lincoln Ave & Diversey Pkwy', '152')
window.stations_ids.set('California Ave & North Ave', '276')
window.stations_ids.set('Damen Ave & Coulter St', '167')
window.stations_ids.set('Canal St & Adams St', '192')
window.stations_ids.set('Wells St & Concord Ln', '289')
window.stations_ids.set('Canal St & Monroe St', '191')
window.stations_ids.set('Ogden Ave & Congress Pkwy', '122')
window.stations_ids.set('State St & 29th St', '193')
window.stations_ids.set('Clinton St & Tilden St', '68')
window.stations_ids.set('Clark St & Leland Ave', '326')
window.stations_ids.set('Clark St & Randolph St', '51')
window.stations_ids.set('Broadway & Sheridan Rd', '256')
window.stations_ids.set('Lake Shore Dr & Belmont Ave', '334')
window.stations_ids.set('Milwaukee Ave & Wabansia Ave', '158')
window.stations_ids.set('Morgan St & 18th St', '14')
window.stations_ids.set('Halsted St & Polk St', '108')
window.stations_ids.set('Wells St & Evergreen Ave', '291')
window.stations_ids.set('Cottage Grove Ave & 43rd St', '271')
window.stations_ids.set('Wood St & Division St', '17')
window.stations_ids.set('Western Ave & Division St', '305')
window.stations_ids.set('Lake Shore Dr & Monroe St', '76')
window.stations_ids.set('Wolcott Ave & Lawrence Ave', '344')
window.stations_ids.set('Clinton St & Lake St', '66')
window.stations_ids.set('State St & Wacker Dr', '194')
window.stations_ids.set('Bissell St & Armitage Ave', '113')
window.stations_ids.set('Wallace Ave & 35th St', '278')
window.stations_ids.set('Emerald Ave & 28th St', '207')
window.stations_ids.set('Adler Planetarium', '341')
window.stations_ids.set('Clarendon Ave & Gordon Ter', '312')
window.stations_ids.set('Ashland Ave & 21st St', '208')
window.stations_ids.set('Sheffield Ave & Willow St', '93')
window.stations_ids.set('Racine Ave & Belmont Ave', '226')
window.stations_ids.set('Fairbanks Ct & Grand Ave', '24')
window.stations_ids.set('State St & 19th St', '178')
window.stations_ids.set('Wabash Ave & Grand Ave', '199')
window.stations_ids.set('Damen Ave & Pierce Ave', '69')
window.stations_ids.set('Loomis St & Lexington St', '320')
window.stations_ids.set('Montrose Harbor', '249')
window.stations_ids.set('Lake Shore Dr & Diversey Pkwy', '329')
window.stations_ids.set('Ashland Ave & Armitage Ave', '58')
window.stations_ids.set('Lincoln Ave & Waveland Ave', '257')
window.stations_ids.set('Damen Ave & Charleston St', '310')
window.stations_ids.set('McClurg Ct & Illinois St', '26')
window.stations_ids.set('Clark St & Lincoln Ave', '141')
window.stations_ids.set('Hampden Ct & Diversey Pkwy', '220')
window.stations_ids.set('Damen Ave & Melrose Ave', '228')
window.stations_ids.set('Aberdeen St & Madison St', '80')
window.stations_ids.set('Lincoln Ave & Roscoe St', '230')
window.stations_ids.set('Southport Ave & Irving Park Rd', '318')
window.stations_ids.set('Indiana Ave & 31st St', '272')
window.stations_ids.set('Martin Luther King Dr & 29th St', '237')