var stationPop = new Map();
stationPop.set("Damen Ave & Coulter St", "0");
stationPop.set("State St & 29th St", "0");
stationPop.set("Indiana Ave & 40th St", "0");
stationPop.set("Ashland Ave & 21st St", "0");
stationPop.set("Halsted St & 37th St", "0");
stationPop.set("Cottage Grove Ave & 43rd St", "0");
stationPop.set("Wallace Ave & 35th St", "0");
stationPop.set("Western Ave & 24th St", "0");
stationPop.set("Calumet Ave & 35th St", "0");
stationPop.set("Cottage Grove Ave & 47th St", "0");
stationPop.set("Damen Ave & Cullerton St", "1");
stationPop.set("Lincoln Ave & Fullerton Ave", "1");
stationPop.set("Wentworth Ave & 24th St", "1");
stationPop.set("Racine Ave & 13th St", "1");
stationPop.set("May St & Cullerton St", "1");
stationPop.set("King Dr & 47th St", "1");
stationPop.set("Western Ave & 21st St", "1");
stationPop.set("Prairie Ave & Garfield Blvd", "1");
stationPop.set("Emerald Ave & 28th St", "1");
stationPop.set("Normal Ave & Archer Ave", "1");
stationPop.set("Wells St & 19th St", "1");
stationPop.set("Rhodes Ave & 32nd St", "1");
stationPop.set("Cottage Grove Ave & Oakwood Blvd", "1");
stationPop.set("Lake Park Ave & 47th St", "1");
stationPop.set("Indiana Ave & 31st St", "1");
stationPop.set("Racine Ave & 15th St", "1");
stationPop.set("Ashland Ave & 13th St", "1");
stationPop.set("Ashland Ave & Grand Ave", "1");
stationPop.set("Morgan St & 31st St", "1");
stationPop.set("Kedzie Ave & Palmer Ct", "1");
stationPop.set("Southport Ave & Clark St", "1");
stationPop.set("Broadway & Argyle St", "1");
stationPop.set("Paulina St & Montrose Ave", "1");
stationPop.set("Lincoln Ave & Belle Plaine Ave", "1");
stationPop.set("Seeley Ave & Roscoe St", "1");
stationPop.set("Clarendon Ave & Gordon Ter", "1");
stationPop.set("Ravenswood Ave & Berteau Ave", "1");
stationPop.set("Leavitt St & Hirsch St", "1");
stationPop.set("Damen Ave & Sunnyside Ave", "1");
stationPop.set("Kimbark Ave & 53rd St", "1");
stationPop.set("Sheridan Rd & Lawrence Ave", "1");
stationPop.set("Lincoln Ave & Addison St", "1");
stationPop.set("Emerald Ave & 31st St", "1");
stationPop.set("Wolcott Ave & Polk St", "1");
stationPop.set("Racine Ave & Wrightwood Ave", "1");
stationPop.set("Lake Park Ave & 56th St", "1");
stationPop.set("Ashland Ave & Grace St", "1");
stationPop.set("California Ave & 21st St", "1");
stationPop.set("Halsted St & Wrightwood Ave", "1");
stationPop.set("Cottage Grove Ave & 51st St", "1");
stationPop.set("Blackstone Ave & Hyde Park Blvd", "2");
stationPop.set("Lincoln Ave & Belmont Ave", "2");
stationPop.set("Halsted St & 21st St", "2");
stationPop.set("Indiana Ave & 26th St", "2");
stationPop.set("State St & 33rd St", "2");
stationPop.set("Calumet Ave & 33rd St", "2");
stationPop.set("Claremont Ave & Hirsch St", "2");
stationPop.set("Campbell Ave & North Ave", "2");
stationPop.set("Paulina St & Diversey Pkwy", "2");
stationPop.set("Clinton St & 18th St", "2");
stationPop.set("Martin Luther King Dr & Oakwood Blvd", "2");
stationPop.set("State St & 35th St", "2");
stationPop.set("Stave St & Armitage Ave", "2");
stationPop.set("Halsted St & 18th St", "2");
stationPop.set("Paulina St & 18th St", "2");
stationPop.set("Halsted St & Archer Ave", "2");
stationPop.set("Leavitt St & North Ave", "2");
stationPop.set("Damen Ave & Madison St", "2");
stationPop.set("Milwaukee Ave & Rockwell St", "2");
stationPop.set("Sedgwick St & Schiller St", "2");
stationPop.set("Martin Luther King Dr & 29th St", "2");
stationPop.set("Ravenswood Ave & Montrose Ave", "2");
stationPop.set("Ashland Ave & Belle Plaine Ave", "2");
stationPop.set("Woodlawn Ave & 55th St", "2");
stationPop.set("Clifton Ave & Lawrence Ave", "2");
stationPop.set("Broadway & Sheridan Rd", "2");
stationPop.set("Lincoln Ave & Waveland Ave", "2");
stationPop.set("Logan Blvd & Elston Ave", "2");
stationPop.set("California Ave & Francis Pl", "2");
stationPop.set("California Ave & North Ave", "2");
stationPop.set("Halsted St & Maxwell St", "2");
stationPop.set("Wood St & Grand Ave", "2");
stationPop.set("Larrabee St & Armitage Ave", "2");
stationPop.set("Broadway & Wilson Ave", "2");
stationPop.set("Broadway & Berwyn Ave", "2");
stationPop.set("Western Ave & Division St", "2");
stationPop.set("Sheridan Rd & Buena Ave", "2");
stationPop.set("Southport Ave & Clybourn Ave", "2");
stationPop.set("Leavitt St & Armitage Ave", "2");
stationPop.set("Damen Ave & Charleston St", "2");
stationPop.set("Wood St & Taylor St", "2");
stationPop.set("Southport Ave & Irving Park Rd", "2");
stationPop.set("Greenview Ave & Diversey Pkwy", "2");
stationPop.set("Loomis St & Lexington St", "2");
stationPop.set("Stockton Dr & Wrightwood Ave", "2");
stationPop.set("Clark St & Leland Ave", "2");
stationPop.set("Halsted St & Blackhawk St", "2");
stationPop.set("Ashland Ave & Blackhawk St", "2");
stationPop.set("Wolcott Ave & Lawrence Ave", "2");
stationPop.set("Ada St & Washington Blvd", "2");
stationPop.set("Western Ave & Winnebago Ave", "3");
stationPop.set("Ashland Ave & Lake St", "3");
stationPop.set("Wentworth Ave & Archer Ave", "3");
stationPop.set("Congress Pkwy & Ogden Ave", "3");
stationPop.set("Blue Island Ave & 18th St", "3");
stationPop.set("Clybourn Ave & Division St", "3");
stationPop.set("Loomis St & Jackson Blvd", "3");
stationPop.set("Damen Ave & Wellington Ave", "3");
stationPop.set("Ashland Ave & Wrightwood Ave", "3");
stationPop.set("Canal St & Harrison St", "3");
stationPop.set("State St & 19th St", "3");
stationPop.set("Greenview Ave & Fullerton Ave", "3");
stationPop.set("Damen Ave & Grand Ave", "3");
stationPop.set("California Ave & Division St", "3");
stationPop.set("May St & Fulton St", "3");
stationPop.set("Halsted St & Willow St", "3");
stationPop.set("Racine Ave & Belmont Ave", "3");
stationPop.set("Damen Ave & Melrose Ave", "3");
stationPop.set("Clark St & Montrose Ave", "3");
stationPop.set("Western Ave & Leland Ave", "3");
stationPop.set("Damen Ave & Leland Ave", "3");
stationPop.set("Lincoln Ave & Leavitt St", "3");
stationPop.set("Ravenswood Ave & Irving Park Rd", "3");
stationPop.set("Clarendon Ave & Junior Ter", "3");
stationPop.set("Shore Drive & 55th St", "3");
stationPop.set("Ashland Ave & Wellington Ave", "3");
stationPop.set("Clarendon Ave & Leland Ave", "3");
stationPop.set("Greenwood Ave & 47th St", "3");
stationPop.set("Pine Grove Ave & Irving Park Rd", "3");
stationPop.set("Kedzie Ave & Milwaukee Ave", "3");
stationPop.set("Hermitage Ave & Polk St", "3");
stationPop.set("Stetson Ave & South Water St", "3");
stationPop.set("Halsted St & 35th St", "3");
stationPop.set("Broadway & Belmont Ave", "3");
stationPop.set("Halsted St & Roscoe St", "3");
stationPop.set("Sheffield Ave & Wrightwood Ave", "3");
stationPop.set("Broadway & Cornelia Ave", "3");
stationPop.set("Halsted St & Waveland Ave", "3");
stationPop.set("Lincoln Ave & Eastwood Ave", "3");
stationPop.set("Clark St & Winnemac Ave", "3");
stationPop.set("Sheffield Ave & Webster Ave", "3");
stationPop.set("Ellis Ave & 58th St", "3");
stationPop.set("Lake Shore Dr & Diversey Pkwy", "3");
stationPop.set("Halsted St & Diversey Pkwy", "3");
stationPop.set("Lake Shore Dr & Belmont Ave", "3");
stationPop.set("Clark St & Chicago Ave", "3");
stationPop.set("Calumet Ave & 18th St", "3");
stationPop.set("Clark St & Wrightwood Ave", "3");
stationPop.set("Adler Planetarium", "3");
stationPop.set("Ashland Ave & Chicago Ave", "3");
stationPop.set("Morgan St & 18th St", "4");
stationPop.set("Racine Ave & 18th St", "4");
stationPop.set("Wood St & North Ave", "4");
stationPop.set("Loomis St & Taylor St", "4");
stationPop.set("May St & Taylor St", "4");
stationPop.set("Orleans St & Elm St", "4");
stationPop.set("Larrabee St & North Ave", "4");
stationPop.set("Larrabee St & Menomonee St", "4");
stationPop.set("Ashland Ave & Augusta Blvd", "4");
stationPop.set("Racine Ave & Congress Pkwy", "4");
stationPop.set("Wabash Ave & Cermak Rd", "4");
stationPop.set("Halsted St & James M Rochford St", "4");
stationPop.set("Clinton St & Roosevelt Rd", "4");
stationPop.set("Clinton St & Tilden St", "4");
stationPop.set("Green St & Milwaukee Ave", "4");
stationPop.set("Eckhart Park", "4");
stationPop.set("Racine Ave & Fullerton Ave", "4");
stationPop.set("Carpenter St & Huron St", "4");
stationPop.set("State St & Pearson St", "4");
stationPop.set("Halsted St & Polk St", "4");
stationPop.set("900 W Harrison", "4");
stationPop.set("Sedgwick St & Huron St", "4");
stationPop.set("Bissell St & Armitage Ave", "4");
stationPop.set("Morgan Ave & 14th Pl", "4");
stationPop.set("Lincoln Ave & Diversey Pkwy", "4");
stationPop.set("Southport Ave & Belmont Ave", "4");
stationPop.set("Milwaukee Ave & Wabansia Ave", "4");
stationPop.set("Clark St & Waveland Ave", "4");
stationPop.set("Wells St & Polk St", "4");
stationPop.set("Damen Ave & Augusta Blvd", "4");
stationPop.set("Ogden Ave & Race Ave", "4");
stationPop.set("Southport Ave & Wrightwood Ave", "4");
stationPop.set("Damen Ave & Cortland Ave", "4");
stationPop.set("Clifton Ave & Armitage Ave", "4");
stationPop.set("Halsted St & Dickens Ave", "4");
stationPop.set("Southport Ave & Waveland Ave", "4");
stationPop.set("Southport Ave & Roscoe St", "4");
stationPop.set("Lincoln Ave & Roscoe St", "4");
stationPop.set("Sheridan Rd & Montrose Ave", "4");
stationPop.set("Sangamon St & Washington Blvd", "4");
stationPop.set("Sheridan Rd & Irving Park Rd", "4");
stationPop.set("Morgan St & Polk St", "4");
stationPop.set("Montrose Harbor", "4");
stationPop.set("Michigan Ave & 18th St", "4");
stationPop.set("Franklin St & Quincy St", "4");
stationPop.set("Wells St & Evergreen Ave", "4");
stationPop.set("Broadway & Barry Ave", "4");
stationPop.set("Clark St & Schiller St", "4");
stationPop.set("Lakeview Ave & Fullerton Pkwy", "4");
stationPop.set("Wabash Ave & 8th St", "4");
stationPop.set("Wilton Ave & Diversey Pkwy", "5");
stationPop.set("Wood St & Division St", "5");
stationPop.set("Sheffield Ave & Kingsbury St", "5");
stationPop.set("Aberdeen St & Jackson Blvd", "5");
stationPop.set("Noble St & Milwaukee Ave", "5");
stationPop.set("Wells St & Walton St", "5");
stationPop.set("Ogden Ave & Chicago Ave", "5");
stationPop.set("Ashland Ave & Armitage Ave", "5");
stationPop.set("Dayton St & North Ave", "5");
stationPop.set("Wood St & Milwaukee Ave", "5");
stationPop.set("McCormick Place", "5");
stationPop.set("Morgan St & Lake St", "5");
stationPop.set("State St & 16th St", "5");
stationPop.set("Jefferson St & Monroe St", "5");
stationPop.set("Aberdeen St & Madison St", "5");
stationPop.set("May St & Randolph St", "5");
stationPop.set("Sheffield Ave & Willow St", "5");
stationPop.set("Green St & Randolph St", "5");
stationPop.set("Sheffield Ave & Addison St", "5");
stationPop.set("Sheffield Ave & Wellington Ave", "5");
stationPop.set("Wilton Ave & Belmont Ave", "5");
stationPop.set("Sedgwick St & North Ave", "5");
stationPop.set("California Ave & Milwaukee Ave", "5");
stationPop.set("Damen Ave & Chicago Ave", "5");
stationPop.set("Damen Ave & Division St", "5");
stationPop.set("Peoria St & Jackson Blvd", "5");
stationPop.set("Sedgwick St & Webster Ave", "5");
stationPop.set("Larrabee St & Webster Ave", "5");
stationPop.set("Fort Dearborn Dr & 31st St", "5");
stationPop.set("Southport Ave & Wellington Ave", "5");
stationPop.set("Clark St & Wellington Ave", "5");
stationPop.set("Lake Shore Dr & Wellington Ave", "5");
stationPop.set("Franklin St & Lake St", "5");
stationPop.set("Michigan Ave & 14th St", "5");
stationPop.set("Canal St & Monroe St", "5");
stationPop.set("State St & Wacker Dr", "5");
stationPop.set("Cityfront Plaza & N Water St", "5");
stationPop.set("Michigan Ave & Madison St", "5");
stationPop.set("Halsted St & Madison St", "5");
stationPop.set("Ashland Ave & Division St", "5");
stationPop.set("St Clair St & Erie St", "5");
stationPop.set("Wells St & Ohio St", "5");
stationPop.set("Hampden Ct & Diversey Pkwy", "5");
stationPop.set("Pine Grove Ave & Addison St", "5");
stationPop.set("Indiana Ave & Roosevelt Rd", "5");
stationPop.set("Lake Shore Dr & North Blvd", "5");
stationPop.set("LaSalle St & Jackson Blvd", "5");
stationPop.set("Michigan Ave & Jackson Blvd", "5");
stationPop.set("Franklin St & Arcade Pl", "5");
stationPop.set("Wells St & Concord Ln", "5");
stationPop.set("State St & Harrison St", "6");
stationPop.set("Fairbanks Ct & Grand Ave", "6");
stationPop.set("Michigan Ave & Pearson St", "6");
stationPop.set("McClurg Ct & Illinois St", "6");
stationPop.set("Franklin St & Chicago Ave", "6");
stationPop.set("State St & Van Buren St", "6");
stationPop.set("Cannon Dr & Fullerton Ave", "6");
stationPop.set("Streeter Dr & Illinois St", "6");
stationPop.set("Franklin St & Jackson Blvd", "6");
stationPop.set("Dearborn St & Adams St", "6");
stationPop.set("Michigan Ave & Washington St", "6");
stationPop.set("State St & Randolph St", "6");
stationPop.set("Michigan Ave & Congress Pkwy", "6");
stationPop.set("State St & Kinzie St", "6");
stationPop.set("Larrabee St & Kingsbury St", "6");
stationPop.set("Dearborn St & Monroe St", "6");
stationPop.set("Clark St & Congress Pkwy", "6");
stationPop.set("Clark St & Randolph St", "6");
stationPop.set("Michigan Ave & Lake St", "6");
stationPop.set("Wells St & Erie St", "6");
stationPop.set("Desplaines St & Kinzie St", "6");
stationPop.set("Wabash Ave & Roosevelt Rd", "6");
stationPop.set("Clinton St & Lake St", "6");
stationPop.set("Sheffield Ave & Fullerton Ave", "6");
stationPop.set("Damen Ave & Pierce Ave", "6");
stationPop.set("Kingsbury St & Erie St", "6");
stationPop.set("Canal St & Jackson Blvd", "6");
stationPop.set("Lake Shore Dr & Monroe St", "6");
stationPop.set("Clinton St & Madison St", "6");
stationPop.set("Daley Center Plaza", "6");
stationPop.set("Michigan Ave & Oak St", "6");
stationPop.set("Millennium Park", "6");
stationPop.set("Clinton St & Washington Blvd", "6");
stationPop.set("Lincoln Ave & Armitage Ave", "6");
stationPop.set("Museum Campus", "6");
stationPop.set("LaSalle St & Washington St", "6");
stationPop.set("Lake Shore Dr & Ohio St", "6");
stationPop.set("Orleans St & Merchandise Mart Plaza", "6");
stationPop.set("State St & Erie St", "6");
stationPop.set("Clark St & North Ave", "6");
stationPop.set("Dearborn Pkwy & Delaware Pl", "6");
stationPop.set("Clark St & Lincoln Ave", "6");
stationPop.set("Mies van der Rohe Way & Chicago Ave", "6");
stationPop.set("Canal St & Madison St", "6");
stationPop.set("Clark St & Elm St", "6");
stationPop.set("Theater on the Lake", "6");
stationPop.set("LaSalle St & Illinois St", "6");
stationPop.set("Canal St & Adams St", "6");
stationPop.set("Columbus Dr & Randolph St", "6");
stationPop.set("Wabash Ave & Grand Ave", "6");
